/* StemPlayer (vanilla) — adapted from the user's Guitar God project.
   Two stems now: a `backing` track (bass+drums+piano+other+vocals merged) that
   always plays, and `guitar` — *your* track, which muffles when you miss, true
   to the original pitch: "hit the notes or drop your guitar track."

   The note chart is generated by onset detection over both stems (no manual
   charting). Audio: NEFFEX "Fight Back" separated by the user's demucs_v4_trt,
   re-mixed down to backing+guitar (see assets/stems/CREDITS.md). */

const STEM_NAMES = ['backing', 'guitar'];
const GUITAR_IDX = 1;
export const LANE_COLORS = ['#22c55e', '#84cc16', '#eab308', '#f59e0b', '#f97316', '#ef4444', '#ec4899', '#a855f7', '#3b82f6', '#06b6d4'];
export const HIT_WINDOW = 0.2;
export const COUNTDOWN = 3.0;

export class StemPlayer {
  constructor(song = 'neffex_fight_back') {
    this.base = `assets/stems/${song}`;
    this.ctx = null;
    this.buffers = [];
    this.booBuffer = null;
    this.sources = [];
    this.gains = [];
    this.guitarGain = null;
    this.startTime = 0;
    this.duration = 0;
  }

  async load(onProgress) {
    if (!this.ctx) this.ctx = new (window.AudioContext || window.webkitAudioContext)();
    if (this.ctx.state === 'suspended') await this.ctx.resume();

    const total = STEM_NAMES.length + 1;
    let done = 0;
    const step = (name) => onProgress && onProgress({ loaded: done, total, currentFile: name });

    step('crowd');
    this.booBuffer = await this.fetchAudio(`${this.base}/boo.mp3`).catch(() => null);
    done++;

    const bufs = [];
    for (const name of STEM_NAMES) {
      step(name);
      bufs.push(await this.fetchAudio(`${this.base}/${name}.mp3`));
      done++; step(name);
    }
    this.buffers = bufs;
    this.duration = Math.max(...bufs.map((b) => b.duration));
    return this.duration;
  }

  async fetchAudio(url) {
    const res = await fetch(url, { cache: 'force-cache' });
    if (!res.ok) throw new Error(`fetch ${url} -> ${res.status}`);
    const arr = await res.arrayBuffer();
    if (!arr.byteLength) throw new Error(`empty ${url}`);
    return await this.ctx.decodeAudioData(arr);
  }

  /** Onset detection over both stems -> [{time, lane}] spread across 5 lanes. */
  analyzeNotes(difficulty = 'medium') {
    if (this.buffers.length < 2) return [];
    const cfg = ({
      easy: { mult: 1.9, gap: 1.0 },
      medium: { mult: 1.2, gap: 0.6 },
      hard: { mult: 0.7, gap: 0.34 },
    })[difficulty] || { mult: 1.9, gap: 1.0 };

    const detect = (buf, threshold) => {
      const data = buf.getChannelData(0);
      const sr = buf.sampleRate;
      const win = Math.floor(sr * 0.05);
      const hop = Math.floor(sr * 0.03);
      let prev = 0, last = -9;
      const out = [];
      for (let i = 0; i < data.length - win; i += hop) {
        let sum = 0;
        for (let j = 0; j < win; j += 4) sum += data[i + j] * data[i + j];
        const e = Math.sqrt(sum / (win / 4));
        if (e > prev * 1.8 && e > threshold) {
          const time = i / sr;
          if (time - last > 0.18) { out.push(time); last = time; }
        }
        prev = e;
      }
      return out;
    };

    // guitar onsets = melody notes; backing onsets = the beat to keep up with
    const guitar = detect(this.buffers[GUITAR_IDX], 0.045 * cfg.mult).map((t) => ({ t, src: 1 }));
    const backing = detect(this.buffers[0], 0.06 * cfg.mult).map((t) => ({ t, src: 0 }));
    const all = guitar.concat(backing).sort((a, b) => a.t - b.t);

    const notes = [];
    let lane = 0, last = -9;
    for (const o of all) {
      if (o.t - last < cfg.gap) continue; // keep it playable
      // spread across all 10 strings; guitar leans to the inner frets
      const l = o.src === 1 ? 2 + (lane % 6) : (lane % 2 ? lane % 10 : (lane * 3) % 10);
      notes.push({ time: o.t, lane: l, id: 'n' + notes.length, hit: false, missed: false });
      lane++; last = o.t;
    }
    return notes;
  }

  play() {
    if (!this.ctx || !this.buffers.length) return;
    if (this.ctx.state === 'suspended') this.ctx.resume();
    this.stop();
    this.sources = []; this.gains = []; this.guitarGain = null;
    const t = this.ctx.currentTime + COUNTDOWN;
    this.startTime = this.ctx.currentTime;
    this.buffers.forEach((buffer, i) => {
      const src = this.ctx.createBufferSource(); src.buffer = buffer;
      const gain = this.ctx.createGain(); gain.gain.value = 1;
      src.connect(gain); gain.connect(this.ctx.destination);
      src.start(t);
      this.sources.push(src); this.gains.push(gain);
      if (i === GUITAR_IDX) this.guitarGain = gain;
    });
  }

  stop() { this.sources.forEach((s) => { try { s.stop(); } catch {} }); this.sources = []; }

  /** any miss drops the guitar (the one mutable stem). */
  muteInstrument(_lane, duration = 4.0) {
    if (!this.ctx || !this.guitarGain) return;
    const g = this.guitarGain, t = this.ctx.currentTime;
    g.gain.cancelScheduledValues(t);
    g.gain.linearRampToValueAtTime(0.12, t + 0.1);
    g.gain.setValueAtTime(0.12, t + duration);
    g.gain.linearRampToValueAtTime(1, t + duration + 1.5);
    if (this.booBuffer && Math.random() > 0.75) {
      const s = this.ctx.createBufferSource(); s.buffer = this.booBuffer;
      const bg = this.ctx.createGain(); bg.gain.value = 0.4;
      s.connect(bg); bg.connect(this.ctx.destination); s.start(t);
    }
  }

  unmuteInstrument() {
    if (!this.ctx || !this.guitarGain) return;
    const g = this.guitarGain, t = this.ctx.currentTime;
    g.gain.cancelScheduledValues(t);
    g.gain.linearRampToValueAtTime(1, t + 0.1);
  }

  getCurrentTime() {
    if (!this.ctx) return -COUNTDOWN;
    return (this.ctx.currentTime - this.startTime) - COUNTDOWN;
  }
}

/** Judge a hit by timing error (seconds). */
export function judge(diff) {
  if (diff < 0.05) return { pts: 100, text: 'PERFECT', tone: '#eab308' };
  if (diff > 0.12) return { pts: 20, text: 'OK', tone: '#22c55e' };
  return { pts: 50, text: 'GOOD', tone: '#3b82f6' };
}
